### PR TITLE
Fixes to javadoc linting errors

### PR DESCRIPTION
**Pull request by matgallacher**
Minor changes to the javadoc to fix the issue https://github.com/google/volley/issues/4

### CODE REVIEW

**Comment by matgallacher** [comment]
I signed it!

**Comment by jpd236** [comment]
Thanks for sending this out - code looks good to me. Let me know if you're having trouble figuring out what needs to be done with the CLA. At a glance, it seems like the commit is associated with an email that isn't tied to any GitHub account, so either changing the commit to use the same email as your GitHub account, or associating that email with your account and signing the CLA with it should resolve the problem.

**Comment by matgallacher** [comment]
Is it possible there was a timing issue with the CLA?

**Comment by jpd236** [comment]
There's a little "?" next to the name at:

https://github.com/google/volley/pull/5/commits/c99606bc48545549cc7a83d8e2c515bf4dde1219

if you hover over it, it mentions the email associated with the commit and says it's not associated with any GitHub account, which seems problematic to me. If you don't think that's related, and the email mentioned there has signed the CLA, then I can look further into it from our side.

**Comment by matgallacher** [comment]
I can't see the "?", if it is showing a gmail.com email it is correct, if it is showing blackbay.com that would be an issue

**Comment by jpd236** [comment]
It's showing @hgl.com. Question mark here, for reference:
screen shot 2017-01-30 at 7 12 13 am

What I'd do is amend your commit with:

`git commit --amend --author="FirstName LastName <email@gmail.com>"`

(editing the author portion as appropriate)

then git push -f to force-push the new commit here. You can edit the name/email for future commits using git config user.name "FirstName LastName" and git config user.email "email@gmail.com" (or add --global to set these as the default for all git repositories on your machine).

**Comment by matgallacher** [comment]
That sounds like a domain thing on my side - I think it might be an idea to abandon this and I'll redo the changes on my personal PC, they really aren't big changes!

**Comment by matgallacher** [comment]
I'm closing this so I can resubmit with the correct details

**Pull request closed without merging**
