### PR TITLE
 Allow sending any JSON in JSONArrayRequest

### PR DESCRIPTION
**Pull request by NotSpooky**
Instead of just arrays.

### CODE REVIEW

**Comment by NotSpooky** [comment]
Already signed the CLA.
Will need to actually clone the project to make unit tests work I guess.

**Comment by jpd236** [comment]
Unfortunately this change would not be backwards compatible in terms of APIs, because JSONArray is not a subclass of JSONObject, so existing callers would break.

You'd need to add a constructor overload instead which takes JSONObject, rather than modifying the existing one.

**Comment by paulsmithkc** [comment]
From a usability standpoint, I've never seen a case where it made sense to send a JSON array as request data over a JSON object.  The problem is that you actually want to send an object and get back an array. But there should be an easy way to implement this without breaking the API.

**Comment by jpd236** [comment]
I'd be happy to review a new PR (or update to this one) which adds a new constructor overload. Not sure what happened to the original author of this one; I didn't mean for my comment to suggest that this was infeasible (hence why it's still open).

**Comment by paulsmithkc** [comment]
New PR created https://github.com/google/volley/pull/406

**Pull request closed without merging**
